### ISSUE TITLE
Master node reboot causes switch back to original slave

### ISSUE THREAD

**Issue by dyoakley** [ClusterLabs/PAF#127]
I realize PAF is designed for an admin and the stated assumption is that pacemaker should not auto start but let the admin get things properly setup first.  However I'm pushing the envelope and trying to build in as much auto recovery as possible once I have a working cluster so I am wanting to autostart pacemaker on bootup of an unfenced node and let my agent sort out what to do with that node.  It seems to me when the agent comes up, it could detect there is already a master online and demote the correct master or rather not bring a new master up at all.  Is this something you guys have contemplated? 

Also is there a discussion forum that would be better for these sorts of questions?

Note below the old master comes back up and then the online master is demoted.  In this case the new master had already process hundreds of additional writes before getting demoted in favor of the master that had gone away for a several minutes.  I also have resource stickiness defaulted to INFINITY (naively thinking that might influence the agent to not bounce the master back to the node it was on prior to the reboot).   Logs are below.
'''
Dec 19 20:35:36 [8622] ff3    pengine:     info: determine_online_status:       Node pghost3 is online
Dec 19 20:35:36 [8622] ff3    pengine:     info: determine_op_status:   Operation monitor found resource pgsqld:0 active on pghost1
Dec 19 20:35:36 [8622] ff3    pengine:     info: determine_op_status:   Operation monitor found resource pgsqld:1 active in master mode on pghost2
Dec 19 20:35:36 [8622] ff3    pengine:     info: determine_op_status:   Operation monitor found resource pgsqld:1 active in master mode on pghost2
Dec 19 20:35:36 [8622] ff3    pengine:     info: clone_print:    Master/Slave Set: pgsql-ha [pgsqld]
Dec 19 20:35:36 [8622] ff3    pengine:     info: short_print:        Masters: [ pghost1 pghost2 ]
Dec 19 20:35:36 [8622] ff3    pengine:     info: short_print:        Slaves: [ pghost3 ]
Dec 19 20:35:36 [8622] ff3    pengine:     info: native_print:  pgsql-master-ip (ocf::heartbeat:IPaddr2):       Started pghost1
Dec 19 20:35:36 [8622] ff3    pengine:     info: master_color:  Promoting pgsqld:1 (Master pghost2)
Dec 19 20:35:36 [8622] ff3    pengine:     info: master_color:  pgsql-ha: Promoted 1 instances of a possible 1 to master
Dec 19 20:35:36 [8622] ff3    pengine:     info: RecurringOp:   Cancelling action pgsqld:0_monitor_10000 (Master vs. Slave)
Dec 19 20:35:36 [8622] ff3    pengine:     info: RecurringOp:    Start recurring monitor (11s) for pgsqld:0 on pghost1
Dec 19 20:35:36 [8622] ff3    pengine:     info: RecurringOp:    Start recurring monitor (10s) for pgsqld:1 on pghost2
Dec 19 20:35:36 [8622] ff3    pengine:     info: RecurringOp:   Cancelling action pgsqld:0_monitor_10000 (Master vs. Slave)
Dec 19 20:35:36 [8622] ff3    pengine:     info: RecurringOp:    Start recurring monitor (11s) for pgsqld:0 on pghost1
Dec 19 20:35:36 [8622] ff3    pengine:     info: RecurringOp:    Start recurring monitor (10s) for pgsqld:1 on pghost2
Dec 19 20:35:36 [8622] ff3    pengine:     info: RecurringOp:    Start recurring monitor (10s) for pgsql-master-ip on pghost2
Dec 19 20:35:36 [8622] ff3    pengine:   notice: LogActions:    Demote  pgsqld:0        (Master -> Slave pghost1)
Dec 19 20:35:36 [8622] ff3    pengine:     info: LogActions:    Leave   pgsqld:1        (Master pghost2)
Dec 19 20:35:36 [8622] ff3    pengine:     info: LogActions:    Leave   pgsqld:2        (Slave pghost3)
Dec 19 20:35:36 [8622] ff3    pengine:   notice: LogActions:    Move    pgsql-master-ip (Started pghost1 -> pghost2)
Dec 19 20:35:36 [8622] ff3    pengine:   notice: process_pe_message:    Calculated transition 25, saving inputs in /var/lib/pacemaker/pengine/pe-input-67.bz2
'''

**Comment by ioguix** [comment]
Hi,

sorry, I have a very low bandwidth right now, I hope to get back to you as soon as possible.

> pacemaker should not auto start but let the admin get things properly setup first

The main issue is not to setup things correctly first, but beeing able to do some inspection after a stonith operation to understand what happen and fix the issues before the node goes back to the cluster. If you start pacemaker on boot, your failling node might bug your cluster again and again and again...Worst, it could fence some other nodes and enter a loop where each node fence the other one after reboot.

> I am wanting to autostart pacemaker on bootup of an unfenced node and let my agent sort out what to do with that node

You will not be able to know if the fencing was triggered because of a PostgreSQL issue, a hardware issue, a network issue, or even a Pacemake issue...As far as I understand this, you will end up rewriting Pacemaker itself inside your agent :/

> Also is there a discussion forum that would be better for these sorts of questions?

The alternative is the Pacemaker user list where you will have a larger audience and some highly skilled people in regard with Pacemaker itself. See users@clusterlabs.org (or https://wiki.clusterlabs.org/wiki/Mailing_lists). I'm following these mailing lists as well regarding to PAF questions.

> Note below the old master comes back up and then the online master is demoted

According to the log and what you describe, I suppose pghost2 came back to the cluster. However, during the probe action on this node, Pacemaker found a master already started on it:

~~~
Dec 19 20:35:36 [8622] ff3 pengine: info: clone_print: Master/Slave Set: pgsql-ha [pgsqld]
Dec 19 20:35:36 [8622] ff3 pengine: info: short_print: Masters: [ pghost1 pghost2 ]
Dec 19 20:35:36 [8622] ff3 pengine: info: short_print: Slaves: [ pghost3 ]
~~~

So, **it did not** promoted it on this node, it was already up and running. As the pgsql-ha setup states, the cluster must host only **one** master, so pengine had to pick one of them to demote it.

You might never join a node with the pgsql instance already up and running. Pacemaker must take care of this to be able to take everything under control. Just make sure to join nodes with a pgsql instance stopped as a standby. Do never join back to the cluster an old master without taking care that it could get back in replication as a standby.
