### ISSUE TITLE
nodename is the best candidate to promote, aborting current promotion

### ISSUE THREAD

**Issue by miro-igov** [ClusterLabs/PAF#187]
Hello, i have cluster of 2 nodes (Ubuntu 18.04) and tried building Postgres Auto Failover as described here: https://clusterlabs.github.io/PAF/Quick_Start-Debian-9-crm.html
I am running pgsql 9.4.
I tried demoting the pgsqlms resource and then promoting it again:
```
crm res demote pgsql-ha
crm res promote pgsql-ha
```
and this threw error 

`exitreason='val-test1-copy is the best candidate to promote, aborting current promotion'`

Looking at corosync log i see this :
```
pgsqlms(pgsqld)[31596]: Mar 09 15:05:39  INFO: Promoting instance on node "val-test2-copy"
pgsqlms(pgsqld)[31596]: Mar 09 15:05:40  INFO: Current node TL#LSN: 192#3221225472
pgsqlms(pgsqld)[31639]: Mar 09 15:05:40  ERROR: val-test1-copy is the best candidate to promote, aborting current promotion
```

Why it ever starts promotion if there is better LSN?

Few lines down in the log i see these lines:
```
pgsqlms(pgsqld)[31754]: Mar 09 15:05:40  INFO: Trying to start failing slave "pgsqld"...
pgsqlms(pgsqld)[31754]: Mar 09 15:05:41  INFO: State is "in archive recovery" after recovery attempt
Mar 09 15:05:41 [26886] val-test2-copy       lrmd:   notice: operation_finished:        pgsqld_notify_0:31754:stderr [ pg_ctl: another server might be running; trying to start server anyway ]
Mar 09 15:05:41 [26886] val-test2-copy       lrmd:   notice: operation_finished:        pgsqld_notify_0:31754:stderr [ pg_ctl: could not start server ]
Mar 09 15:05:41 [26886] val-test2-copy       lrmd:   notice: operation_finished:        pgsqld_notify_0:31754:stderr [ Examinethe log output. ]
```
Why it considers pgsqld as failing slave? It was slave as result of demote command previously.

Then it stops pgsqld:
```
Mar 09 15:05:41 [26886] val-test2-copy       lrmd:     info: log_execute:       executing - rsc:pgsqld action:stop call_id:136
Mar 09 15:05:41 [26889] val-test2-copy       crmd:   notice: process_lrm_event: Result of notify operation for pgsqld on val-test2-copy: 0 (ok) | call=135 key=pgsqld_notify_0 confirmed=true cib-update=0
pgsqlms(pgsqld)[31774]: Mar 09 15:05:42  INFO: Instance "pgsqld" stopped
```

Any help will be appreciated.

**Comment by ioguix** [comment]
Hi,

I'm not sure of the behavior of the `crm res demote` command on the cluster setup.

After the demote action, could you please post the result of these commands:

~~~
cibadmin --query --scope configuration
crm_simulate -sL
~~~

Thanks,

**Comment by miro-igov** [comment]
Hello, i am attaching 2 text files with the command outputs as you requested.
[simulate.txt](https://github.com/ClusterLabs/PAF/files/6129532/simulate.txt)
[config.txt](https://github.com/ClusterLabs/PAF/files/6129533/config.txt)

**Comment by ioguix** [comment]
Hi,

Thanks for the commands and output. So it appears crm sets `target-role=Slave` to pgsql-ha. For information and my own memory, here is the equivalent with pcs:

~~~
pcs resource meta pgsqld-clone target-role=Slave
~~~

But in fact, I really discovered I gave you a wrong command when quickly talking on IRC to set the promotion score to the standby node. It should have been:

~~~
crm_master --node=val-test2-copy --resource=pgsqld --update=2000
~~~

Here is the command to remove the wrong node attribute:
~~~
crm_master --node=val-test2-copy --resource=pgsql-ha --delete
~~~

So, your full procedure should be:

~~~
crm res demote pgsql-ha
crm_master --node=val-test2-copy --resource=pgsqld --update=2000
crm res promote pgsql-ha
~~~

I tested on my side, using pcs, it becomes:

~~~
pcs resource meta pgsqld-clone target-role=Slave
crm_master --node=srv2 --resource=pgsqld --update=2000
pcs resource meta pgsqld-clone target-role=
~~~

**Comment by ioguix** [comment]
For memory, as discussed on IRC with @miro-igov, when you demote a pgsql primary to standby, it then reports back to the cluster a LSN at the start of the current WAL. Eg, if your last LSN was `0/C0005868`, the old primary reports `0/C0000000` after demotion, effectively making it late compared to other standby. By the way, this is completely safe from the PostgreSQL perspective, but the explanation is out of the scope of this issue.

After setting `target-role=Slave`, the promotion scores does not change in the cluster. The cluster keeps them, but make sure no clone are promoted because of the targeted role.

At this point, we have a contradiction between what PostgreSQL clone reports as LSN and the promotion scores in Pacemaker, leading to the error @miro-igov is experiencing:

~~~
Node              real LSN     reported LSN   promotion score
val-test1-copy    0/C0005868   0/C0000000     1001
val-test2-copy    0/C0005868   0/C0005868     1000
~~~

I'm not sure if this is something we can fix from PAF source code itself at this point.

**Comment by miro-igov** [comment]
Why not PAF resource agent queries the LSN first and then decide which node to promote?

I tested by stopping virtual machine val-test1-copy while it was slave. Once the VM was started and pacemaker started, it did the same issue: stopped the working master pgsql-ha on val-test2-copy then started pgsql-ha on both nodes val-test2-copy and val-test1-copy, tried promoting pgsql-ha on val-test2-copy as it was originally before VM stop and thew error that val-test1-copy is the best candidate and promoted it.

Obviously it first tries to promote by score, considering the last master should be the current master but then it checks the LSN.
More logical is checking LSN and then select master candidate.

**Comment by ioguix** [comment]
> Why not PAF resource agent queries the LSN first and then decide which node to promote?

Because RA can not work this way. This is not its job.

The RA doesn't decide what clone to promote, neither when to promote it. Each RA on each clone _can_ reports scores when appropriate, on its own, independently to each others. On top of that, the cluster decide what to do with these scores, based on the cluster state and setup.

The RA responsibility is to report and manage __local__ service status. So RAs are not supposed to connect with each other services to decide what score they should set. This would be wrong, relying to each others availability to deduce cluster state, facing lot of race conditions, etc.

> I tested by stopping virtual machine val-test1-copy. Once the VM was started and pacemaker started, it did the same issue: stopped the working master pgsql-ha on val-test2-copy [...]

This is strange. I did the same test on my side, with pgsql 13, 9.5 and 9.4 and I could reproduce. After a `poweroff` on a standby, I boot it again and start Pacemaker by hands. The node always came back to the cluster and resources on other nodes hasn't been stopped/started again.

> Obviously it first tries to promote by score, considering the last master should be the current master but then it checks the LSN.
More logical is checking LSN and then select master candidate.

This is because for some reason your primary resource has been (gracefully) demoted and reports a lagging LSN. But it shouldn't have been stopped at the first place...
