### ISSUE TITLE
Stale DB instance getting promoted when there is a master recovery

### ISSUE THREAD

**Issue by rag-code** [ClusterLabs/PAF#195]
When the logic with warning log message "This is a master recovery!" is hit, seems like DB with stale data(lower LSN than another) can get promoted.
Steps that reproduced this:
1. Setup: 3 node cluster with DB replication enabled
2. Kill primary so one of the other nodes gets promoted. Make sure this killed primary stays down until explicitly enabled
3. Execute DB updates against new primary which also gets replicated to other available secondary
4. Re-enable the node that was killed as part of step 2 above so it is reachable again and at the same time kill the new primary that was elected as part of step 2
5. Subsequent promotion logic started promoting the re-enabled node(in step 4) and found LSN of the node that was never killed so far to have a better LSN and aborted current promotion
6. The subsequent pgsql_notify_pre_promote hit this warning - "This is a master recovery!" on all reachable nodes and eventually the node with lower LSN(re-enabled in step 4) got promoted.
7. Able to repro this problem everytime.

Tried commenting lines 2184 and 2185(below). This ensured that node with best LSN always got promoted:
```
_set_priv_attr( 'recover_master', '1' )
       if $OCF_NOTIFY_ENV{'promote'}[0]{'uname'} eq $nodename;
```

Is this a known problem? 
What is the guidance?

Thanks

**Comment by ioguix** [comment]
Hi,

> Is this a known problem?

No

> What is the guidance?

I would be interested to know if this is a real life failure and if yes, I would like to have further detailed about the failures.

Your step 4 is in fact not supported because it involves two distinct failures in the same time: 

  1. rejoin of the old failing primary that was supposed to be out of the cluster
  2. failure of the current primary in the same time

We can not deal with two different failures in the same time. Moreover, admins are supposed to resync old primary before rejoining it, this is documented: https://clusterlabs.github.io/PAF/administration.html#rebuild-the-failed-postgresql-instance

Regards,

**Comment by rag-code** [comment]
@ioguix Thanks a lot for your response. I appreciate it.

To your question about this being a real failure, yes, it is. We have 3 node clusters that have experienced the below:
1. Primary in a 3 node cluster went down
2. We have a functioning cluster with 2 nodes now.
3. Repairs were done to recover failed node 
4. As the recovered node was coming up, the primary elected after step 1 was network partitioned due to a glitch
5. This created the condition for stale instance promotion
6. The occurrence is rare but we had a couple of instances

Hope this helps.

Also, regarding the change made to comment lines 2184 and 2185 below:
`_set_priv_attr( 'recover_master', '1' )
       if $OCF_NOTIFY_ENV{'promote'}[0]{'uname'} eq $nodename;`

Do you have any feedback? Commenting this ensured we always promoted node with better LSN

**Comment by ioguix** [comment]
Hi,

What are the actions taken during your step 3 to recover the failed node? Because it is found as a failed primary, I understand it wasn't resync'ed as secondary against the new primary.

> Also, regarding the change made to comment lines 2184 and 2185 below: [...]
> Do you have any feedback? Commenting this ensured we always promoted node with better LSN

I can not comment right now. As far as I currently understand, this might be a misunderstanding or procedure problem, not a logic issue in the code.

**Comment by ioguix** [comment]
This issue is stalling since a long time now.

Feel free to reopen if you have some more infos...

Regards,
