### ISSUE TITLE
Failover aborted due to error when trying to stop already stopped old primary

### ISSUE THREAD

**Issue by bgK** [ClusterLabs/PAF#205]
We recently encountered an unexpected behavior with our PAF managed three node PostgreSQL 10.4 cluster.

Initial situation:
* pg1: postgresql is started, running as primary
* pg2: postgresql is started, running as replica
* pg3: postgresql is started, running as replica

Events:
1. The filesystem where the WALs are stored on node pg1 becomes full.
2. postgresql crashes on node pg1 due to not being able to write WALs.
3. pacemaker detects postgresql has failed on node pg1 and decides to recover it. It starts it in replica mode, and issues `pg_ctl promote`.
4. postgresql crashes again on node pg1 due to not being able to write WALs, before being promoted to primary.
5. the promote operation on pg1 times out after 60s.
6. pacemaker tries to failover to node pg2, which is aborted due to not being able to stop postgresql on node pg1. The error is `Instance "pgsql" controldata indicates a running secondary instance, the instance has probably crashed`. (Actually at this point postgresql it is already stopped on node pg1 after having crashed).
7. pacemaker retries the failover to node pg2 multiple times with the same outcome before giving up.

Final situation:
* pg1: postgresql is crashed, configured as replica
* pg2: postgresql is started, running as replica
* pg3: postgresql is started, running as replica

I would have expected pacemaker to restore the cluster to a working state using nodes pg2 and pg3.

---
Cluster resources (nominal state)
```
# pcs status
Cluster name: pgsql_cluster
WARNING: no stonith devices and stonith-enabled is not false
Stack: corosync
Current DC: pg1 (version 1.1.16-10.el7-94ff4df) - partition with quorum
Last updated: Thu Apr 21 17:58:50 2022
Last change: Tue Apr 19 12:25:09 2022

3 nodes configured
5 resources configured

Online: [ pg1 pg2 pg3 ]

Full list of resources:

 vip-master	(ocf::heartbeat:IPaddr2):	Started pg1
 Master/Slave Set: master-postgresql [pgsql]
     Masters: [ pg1 ]
     Slaves: [ pg2 pg3 ]
 vip-slave-sync	(ocf::heartbeat:IPaddr2):	Started pg2

Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled
```
---
Versions
* Pacemaker: 1.1.16-10.el7
* Corosync: 2.4.0
* Pcs: 0.9.158
* PAF: 2.2.0

**Comment by Markus-** [comment]
You definitely should configure fencing.

Am 21.04.2022 um 18:16 schrieb Bastien Bouclet ***@***.***>:

﻿

We recently encountered an unexpected behavior with our PAF managed three node PostgreSQL 10.4 cluster.

Initial situation:

  *   pg1: postgresql is started, running as primary
  *   pg2: postgresql is started, running as replica
  *   pg3: postgresql is started, running as replica

Events:

  1.  The filesystem where the WALs are stored on node pg1 becomes full.
  2.  postgresql crashes on node pg1 due to not being able to write WALs.
  3.  pacemaker detects postgresql has failed on node pg1 and decides to recover it. It starts it in replica mode, and issues pg_ctl promote.
  4.  postgresql crashes again on node pg1 due to not being able to write WALs, before being promoted to primary.
  5.  the promote operation on pg1 times out after 60s.
  6.  pacemaker tries to failover to node pg2, which is aborted due to not being able to stop postgresql on node pg1. The error is Instance "pgsql" controldata indicates a running secondary instance, the instance has probably crashed. (Actually at this point postgresql it is already stopped on node pg1 after having crashed).
  7.  pacemaker retries the failover to node pg2 multiple times with the same outcome before giving up.

Final situation:

  *   pg1: postgresql is crashed, configured as replica
  *   pg2: postgresql is started, running as replica
  *   pg3: postgresql is started, running as replica

I would have expected pacemaker to restore the cluster to a working state using nodes pg2 and pg3.

________________________________

Cluster resources (nominal state)

# pcs status
Cluster name: pgsql_cluster
WARNING: no stonith devices and stonith-enabled is not false
Stack: corosync
Current DC: pg1 (version 1.1.16-10.el7-94ff4df) - partition with quorum
Last updated: Thu Apr 21 17:58:50 2022
Last change: Tue Apr 19 12:25:09 2022

3 nodes configured
5 resources configured

Online: [ pg1 pg2 pg3 ]

Full list of resources:

 vip-master     (ocf::heartbeat:IPaddr2):       Started pg1
 Master/Slave Set: master-postgresql [pgsql]
     Masters: [ pg1 ]
     Slaves: [ pg2 pg3 ]
 vip-slave-sync (ocf::heartbeat:IPaddr2):       Started pg2

Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled


________________________________

Versions

  *   Pacemaker: 1.1.16-10.el7
  *   Corosync: 2.4.0
  *   Pcs: 0.9.158
  *   PAF: 2.2.0

**Comment by bgK** [comment]
> You definitely should configure fencing.

Sure. This is hosted on a shared virtual hosting system, so I suppose I could have a virtual watchdog device added to the VMs and set up sbd.

I can see how fencing would have helped in the situation of this issue. sdb would have let the watchdog trip after postgresql stayed in a failed state on node pg1. The system would have rebooted. The cluster would have been able to safely assume postgresql to be stopped and proceed with the failover to node pg2.

For this issue, though, there are no connectivity problems between the nodes at any point. Shouldn't the cluster be able accurately detect the state of the resources and take the required actions without having to rely on fencing?
What I don't understand is why PAF does not successfully perform the stop operation on node pg1 in the step 6 above. Could it not detect that the postgresql processes are already not running and do nothing?

**Comment by ioguix** [comment]
> What I don't understand is why PAF does not successfully perform the stop operation on node pg1 in the step 6 above. Could it not detect that the postgresql processes are already not running and do nothing?

PAF makes several sanity state checks before almost all actions, even the stop action. That means that if Pacemaker call the stop action, PAF should find the instance up and running correctly. If this test fails or find the instance in an incoherent state, PAF immediately rise an error, leading to a fencing decision from Pacemaker (unless you played with fire and change this pacemaker setup). See: https://github.com/ClusterLabs/PAF/blob/78328c6cc1960e1fd3feeaec44c8c179af5b6920/script/pgsqlms#L1542-L1554

This is a bit brutal and stricter than the resource agent specs (OCF), but this is safer. How could we define with no race conditions, no wrong assumption and with a simple code that a PostgreSQL instance is really not running, about to come back or had just a hick-up when the agent was called?

We have been hesitating since day 1 about relaxing the tests around the stop action as this is a major pain point for new users  and frequently asked. However, we want to keep this agent to be robust and as easy to setup as possible, with very few parameters. That's why we are a bit reluctant to add some more obscure/magic options to the resource agent to change how to react.

Last but not least, fencing is mandatory for database HA anyway, so we prefer to keep the code clean, easy to understand and predictable...

Maybe we should add this to the FAQ. What do you think?

I hope this answer your question.
